name: Publish on GitHub, CurseForge & Modrinth

env:
  JAVA_VERSION: 17

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JAVA ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: MC Dungeons Enchantments - ${{ github.event.release.tag_name }}
          github-token: ${{ github.token }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
