name: Publish on GitHub, CurseForge & Modrinth

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17

permissions:
  contents: write

on: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
